# Generated by Django 4.1.2 on 2022-10-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PayImages', '0001_initial'),
        ('AliadosImg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SecHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subTitle', models.CharField(max_length=150)),
                ('bacIcon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SecAliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aliados_Img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AliadosImg.aliadosimg')),
            ],
        ),
        migrations.CreateModel(
            name='payMethos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_Images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PayImages.payimages')),
            ],
        ),
    ]
