# Generated by Django 4.1.3 on 2022-11-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PayImages', '0001_initial'),
        ('AliadosImg', '0001_initial'),
        ('InfoLpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymethos',
            name='Pay_Images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PayImages.payimages'),
        ),
        migrations.AlterField(
            model_name='secaliados',
            name='Aliados_Img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AliadosImg.aliadosimg'),
        ),
    ]
